### ISSUE TITLE
As developer, I want to connect with StUF-BG to retrieve data

### ISSUE THREAD

**Issue by joeribekker** [maykinmedia/open-personen#16] opened 2020-07-31 16:46 UTC
See specs here: https://www.gemmaonline.nl/index.php/Sectormodel_Basisgegevens:_StUF-BG

The connection parameters, XML Zender and Ontvanger needs to be configurable. This can be done via environment variables, I think. If we ended up having an admin anyway, we can also make it into a solo model.

**Comment by shea-maykinmedia** [comment] 2020-09-04 09:53
@joeribekker Was there more to this ticket than making the connection parameters configurable?  If not then I think ticket is covered by https://github.com/maykinmedia/open-personen/issues/60

**Comment by shea-maykinmedia** [comment] 2020-09-14 12:47
This is a duplicate of #60

**Closed by shea-maykinmedia** 2020-09-14 12:47 UTC
Labels: feature, stuf-bg
